var express = require("express");
var router = express.Router();
var short = require('shortid');
var mysql = require('mysql');

var bodyParser = require('body-parser');
var urlencodedParser = bodyParser.urlencoded({limit: '50mb', extended: false});

var con = mysql.createConnection({
    host: "localhost",
    user: "lucasjh",
    password: "Jinhong253",
    database: "dcard_hw0"
});

router.post('/url',urlencodedParser, function(req, res, next) {
    response = 
    {
        url:req.body.url,
        expireAt:req.body.expireAt
    };

    var shortId = short(); //create a shorten_url by random
    var shortenUrl = 'http://35.77.213.217:8000/' + shortId;

    var sql = "INSERT INTO shorten_url VALUES (?)";
    var values = [shortId, shortenUrl, response.url, response.expireAt];
    con.query(sql, [values], function (err, result) {
        if (err) throw err;
        console.log("Number of records inserted: " + result.affectedRows);
    }); 

    console.log({_id:shortId, shortUrl:shortenUrl}, '\n');
    res.send({_id:shortId, shortUrl:shortenUrl}); 
});

router.get('/:url_id', function(req, res, next) {

    var url_id = req.params.url_id;

    if(url_id.length != 9) //when shorten_id is not equal to 9, it is not generated by us
    { 
        res.status(404).send('<h1>Wrong Length of Shorten_url</h1>');
        return;
    }

    var sql = 'SELECT url FROM shorten_url WHERE id_shorten = ' + mysql.escape(url_id);

    con.query(sql, function (err, result) {
        if (err) throw err;

        if(result.length <= 0) //when it response a null, it doesn't exist
        {
            res.status(404).send("<h1>Shorten_url Doesn't Exist</h1>").end();
            return;
        }

        if(result[0].expiredAt < new Date()) //when it expired, response 404
        {
            res.status(404).send('<h1>Link Expired</h1>').end();
            return;
        }

        console.log('\nResult sent');
        res.redirect(result[0].url); 
    });       
});

module.exports = router;